'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowRight, LockKeyhole, ShieldCheck } from 'lucide-react';
export default function Login() {
  const router = useRouter(); const [mode, setMode] = useState<'code'|'owner'>('code'); const [code, setCode] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); setLoading(true); setError(''); try { const response = await fetch(mode === 'code' ? '/api/auth/code' : '/api/auth/owner', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(mode === 'code' ? { code } : { email, password }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Sign in failed'); router.push(mode === 'code' ? '/jobs' : '/admin/status'); router.refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Sign in failed'); } finally { setLoading(false); } }
  return <main className="min-h-screen grid lg:grid-cols-2"><section className="hidden lg:flex flex-col justify-between bg-[#1e2228] text-white p-14"><div className="text-xl font-semibold tracking-tight">✦ Aurelius</div><div><div className="text-sm uppercase tracking-[.25em] text-[#a8b0b7] mb-5">Job Intelligence Portal</div><h1 className="text-5xl font-semibold leading-tight max-w-lg">Opportunity, organized.</h1><p className="text-[#b5bbc2] text-lg mt-6 max-w-md leading-relaxed">A focused workspace for discovering and tracking your next great role.</p></div><div className="text-sm text-[#858e98]">Your next opportunity is already out there.</div></section><section className="flex items-center justify-center p-6"><div className="w-full max-w-md"><div className="lg:hidden text-xl font-bold mb-12">✦ Aurelius</div><div className="w-12 h-12 rounded-xl bg-[#e7f3eb] text-[#26824c] flex items-center justify-center mb-7"><LockKeyhole size={22}/></div><h2 className="text-3xl font-semibold tracking-tight">Welcome to Aurelius</h2><p className="text-[#7c848e] mt-2">Sign in to your job intelligence portal.</p><div className="grid grid-cols-2 bg-[#e9ebee] rounded-xl p-1 mt-8 mb-7"><button onClick={() => { setMode('code'); setError(''); }} className={`py-2.5 rounded-lg text-sm font-semibold ${mode === 'code' ? 'bg-white shadow-sm' : 'text-[#78808a]'}`}>Access Code</button><button onClick={() => { setMode('owner'); setError(''); }} className={`py-2.5 rounded-lg text-sm font-semibold ${mode === 'owner' ? 'bg-white shadow-sm' : 'text-[#78808a]'}`}>Owner Login</button></div><form onSubmit={submit} className="space-y-4">{mode === 'code' ? <label className="block text-sm font-semibold">Access code<input className="input mt-2" value={code} onChange={e => setCode(e.target.value)} placeholder="AUR-XXXXXXXXXX" required autoComplete="off" /></label> : <><label className="block text-sm font-semibold">Email<input className="input mt-2" type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@example.com" required /></label><label className="block text-sm font-semibold">Password<input className="input mt-2" type="password" value={password} onChange={e => setPassword(e.target.value)} required /></label></>}{error && <p role="alert" className="text-sm text-red-600">{error}</p>}<button disabled={loading} className="button w-full flex justify-center items-center gap-2">{loading ? 'Signing in…' : 'Continue'} <ArrowRight size={16}/></button></form><p className="mt-8 text-sm text-[#8b929a] flex items-center gap-2"><ShieldCheck size={16}/> Secure access to your workspace</p></div></section></main>;
}
